name: Dash App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Google Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip xvfb
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION%%.*}")
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$DRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install "dash[testing]"
          pip install dash-bootstrap-components
          pip install pandas
          pip install plotly

      - name: Run Dash tests
        env:
          DASH_TEST_HEADLESS: "1"
          DASH_TEST_BROWSER: "chrome"
          _DASH_TEST_CHROME_PATH: "/usr/bin/google-chrome"
          DASH_TEST_CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
          DASH_TEST_CHROME_OPTIONS: "--headless=new --no-sandbox --disable-dev-shm-usage"
        run: |
          pytest -q test_app.py --disable-warnings --maxfail=2


